version: '3'
services:
  web:
    container_name: odoo_web
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    container_name: data
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
