version: '3'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8060-8062:8069"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
